name: Wii
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.wii2 -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: GenPlusGX-wii
        path: |
          ./*.dol
