name: mGBA-Wii
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        cd src/platform/wii
        cmake -DCMAKE_TOOLCHAIN_FILE=CMakeToolchain.txt
        make
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: mGBA-Wii
        path: |
          ./*.dol
